FROM nvidia/cuda:8.0-cudnn6-devel-ubuntu16.04

MAINTAINER Kshitiz Sharma <kshitizsharma38@gmail.com>

# Install some dependencies
RUN apt-get update && apt-get install -y \
		bc \
		build-essential \
		cmake \
		curl \
		g++ \
		gfortran \
		git \
		libffi-dev \
		libfreetype6-dev \
		libhdf5-dev \
		libjpeg-dev \
		liblcms2-dev \
		libopenblas-dev \
		liblapack-dev \
		libopenjpeg-dev \
		libpng12-dev \
		libssl-dev \
		libtiff5-dev \
		libwebp-dev \
		libzmq3-dev \
		nano \
		pkg-config \
		python-dev \
		software-properties-common \
		unzip \
		vim \
		wget \
		zlib1g-dev \
		qt5-default \
		libvtk6-dev \
		zlib1g-dev \
		libjpeg-dev \
		libwebp-dev \
		libpng-dev \
		libtiff5-dev \
		libjasper-dev \
		libopenexr-dev \
		libgdal-dev \
		libdc1394-22-dev \
		libavcodec-dev \
		libavformat-dev \
		libswscale-dev \
		libtheora-dev \
		libvorbis-dev \
		libxvidcore-dev \
		libx264-dev \
		yasm \
		libopencore-amrnb-dev \
		libopencore-amrwb-dev \
		libv4l-dev \
		libxine2-dev \
		libtbb-dev \
		libeigen3-dev \
		python-dev \
		python-tk \
		python-numpy \
		python3-dev \
		python3-tk \
		python3-numpy \
		ant \
		unzip \
		rsync \
		zsh \
		default-jdk \
		doxygen \
		libfreetype6-dev \
		libboost-all-dev \
		libgflags-dev \
		libgoogle-glog-dev \
		libleveldb-dev \
		libhdf5-dev \
		liblmdb-dev \
		libopencv-dev \
		libprotobuf-dev \
		libsnappy-dev \
		protobuf-compiler \
		python-numpy \
		python-scipy \
		python-nose \
		python-h5py \
		python-skimage \
		python-matplotlib \
		python-pandas \
		python-sklearn \
		python-sympy \
		&& \
		apt-get clean && \
		apt-get autoremove && \
		rm -rf /var/lib/apt/lists/* && \
		update-alternatives --set libblas.so.3 /usr/lib/openblas-base/libblas.so.3 && \
		curl -O https://bootstrap.pypa.io/get-pip.py && \
		python get-pip.py && \
		rm get-pip.py && \
		pip --no-cache-dir install --upgrade ipython && \
		pip --no-cache-dir install \
		ipython \
		pyopenssl \
		ndg-httpsclient \
		pyasn1 \
		pydot-ng \
		Cython \
		ipykernel \
		jupyter \
		path.py \
		futures \
		tqdm \
		flask \
		instagram-scraper \
		clarifai \
		Pillow \
		pygments \
		six \
		sphinx \
		wheel \
		zmq
